services:
  book_manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    command: sh -c "alembic upgrade head && uvicorn src.presentation.api.asgi:asgi --host 0.0.0.0 --port 8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://backend:backend@book_manager_database:5432/books
      - MESSAGE_BROKER_URL=amqp://guest:guest@book_manager_rabbitmq:5672
    depends_on:
      - book_manager_database
      - book_manager_rabbitmq

  book_manager_database:
    image: postgres:14-alpine
    restart: unless-stopped
    container_name: book_manager_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
      - POSTGRES_HOST=book_manager_database
      - POSTGRES_PORT=5432
    volumes:
      - book_manager_database:/var/lib/postgresql/data

  book_manager_rabbitmq:
    image: rabbitmq:3.11.2-alpine
    restart: always
    container_name: book_manager_rabbitmq
    ports:
      - "5672:5672"

volumes:
  book_manager_database:
