"""Added books table

Revision ID: 614fb2d20377
Revises: 
Create Date: 2022-10-15 17:33:06.518737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "614fb2d20377"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("author_full_name", sa.String(length=128), nullable=False),
        sa.Column("genre", sa.String(length=128), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books")
    # ### end Alembic commands ###
